---
- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart dhcp server
  service: name=isc-dhcp-server state=restarted

- name: refresh iptables
  command: /usr/sbin/rebuild-iptables

