---
  - name: install asterisk
    apt: pkg=asterisk state=present

  - name: configure sip.conf
    template: src=sip.conf.j2 dest=/etc/asterisk/sip.conf owner=asterisk
    notify: restart asterisk

  - name: configure extensions.conf
    template: src=extensions.conf.j2 dest=/etc/asterisk/extensions.conf owner=asterisk
    notify: restart asterisk

  - name: check permissions
    raw: find /var/lib/asterisk -user root | wc -l
    register: check_perm

  - name: fix permissions
    shell: chown -R asterisk:asterisk /var/lib/asterisk/
    when: check_perm.stdout_lines[0]|int > 0

