---
  - name: install asterisk
    apt: pkg=asterisk state=present

  - name: configure sip.conf
    template: src=sip.conf.j2 dest=/etc/asterisk/sip.conf owner=asterisk
    notify: restart asterisk

  - name: configure extensions.conf
    template: src=extensions.conf.j2 dest=/etc/asterisk/extensions.conf owner=asterisk
    notify: restart asterisk

  - name: check etc permissions
    shell: find /etc/asterisk -user root | wc -l
    always_run: yes
    register: check_etc_perm

  - name: fix etc permissions
    shell: chown -R asterisk:asterisk /etc/asterisk/
    when: check_etc_perm.stdout_lines[0]|int > 0

  - name: check varlib permissions
    shell: find /var/lib/asterisk -user root | wc -l
    always_run: yes
    register: check_varlib_perm

  - name: fix varlib permissions
    shell: chown -R asterisk:asterisk /var/lib/asterisk/
    when: check_varlib_perm.stdout_lines[0]|int > 0

